// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDM0EWuR02B6yU1hZcmYlF8GEwdIATttI',
    appId: '1:26276679963:web:216e2e4a3eef95acfa83be',
    messagingSenderId: '26276679963',
    projectId: 'sripedia-2a129',
    authDomain: 'sripedia-2a129.firebaseapp.com',
    databaseURL: 'https://sripedia-2a129-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sripedia-2a129.firebasestorage.app',
    measurementId: 'G-K4NYEBMNB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZD2nqhoFUJl_NOaGGf1c8dZLyvMVTNbI',
    appId: '1:26276679963:android:56dc73354217b55dfa83be',
    messagingSenderId: '26276679963',
    projectId: 'sripedia-2a129',
    databaseURL: 'https://sripedia-2a129-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sripedia-2a129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLOZGIsbEex_UT4P__jxoyBLNXs3X-8rU',
    appId: '1:26276679963:ios:fc9358c31b7a0652fa83be',
    messagingSenderId: '26276679963',
    projectId: 'sripedia-2a129',
    databaseURL: 'https://sripedia-2a129-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sripedia-2a129.firebasestorage.app',
    iosBundleId: 'com.example.mainapptest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLOZGIsbEex_UT4P__jxoyBLNXs3X-8rU',
    appId: '1:26276679963:ios:fc9358c31b7a0652fa83be',
    messagingSenderId: '26276679963',
    projectId: 'sripedia-2a129',
    databaseURL: 'https://sripedia-2a129-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sripedia-2a129.firebasestorage.app',
    iosBundleId: 'com.example.mainapptest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDM0EWuR02B6yU1hZcmYlF8GEwdIATttI',
    appId: '1:26276679963:web:7a25e44d36f9d1eefa83be',
    messagingSenderId: '26276679963',
    projectId: 'sripedia-2a129',
    authDomain: 'sripedia-2a129.firebaseapp.com',
    databaseURL: 'https://sripedia-2a129-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sripedia-2a129.firebasestorage.app',
    measurementId: 'G-729TDGE6HX',
  );
}
